# Generated by Django 2.2.24 on 2021-12-13 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
<<<<<<< HEAD
        ("mainapp", "0006_product_is_active"),
=======
        ('mainapp', '0006_product_is_active'),
>>>>>>> a618191eb1b029e26c1bc97a38a86eab7bed6b2e
    ]

    operations = [
        migrations.AlterField(
<<<<<<< HEAD
            model_name="product",
            name="is_active",
            field=models.BooleanField(db_index=True, default=True, verbose_name="продукт активен"),
        ),
        migrations.AlterField(
            model_name="productcategory",
            name="is_active",
            field=models.BooleanField(db_index=True, default=True, verbose_name="категория активна"),
=======
            model_name='product',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, verbose_name='продукт активен'),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, verbose_name='категория активна'),
>>>>>>> a618191eb1b029e26c1bc97a38a86eab7bed6b2e
        ),
    ]
